### ISSUE TITLE
[QUESTION] Patch/modify values when used in a base

### ISSUE THREAD

**Issue by jskrzypek** [mgoltzsche/khelm#22]
I am using this plugin because it allows me to use helm charts inside of a kustomize base and then overlay last-mile config changes on the khelm-rendered resources in consumer kustomizations. The benefit of this is that I can have multiple instances of the helm app, and only modify the core shared config (e.g. the version or standard helm values) in one place.  It works great! Thank you very much for this plugin! :tada: :beers: 

There's one thing I find myself frustrated by, and I wonder if you think there may be a workaround. Because the values are parsed and consumed by the generator itself, I can't patch or otherwise modify them from the downstream kustomization files that consume the base. Is there any way to make this work with the current version of khelm that doesn't involve just putting the ChartRenderer resource in the consumers? If not is there some way to add a feature to khelm, e.g. add a transformer or a meta-generator, that would do the trick? If I'm SOL, then so be it, I have a way to work with it, it's just kind of verbose and I find it ugly :shrug: 

What I am doing currently is: consume the base, use a default/placeholder for the value I want to change, and then overlay patches for the resources that receive that value in the helm template. The problem with this solution that bugs me is when a single value is consumed in multiple resources. In the case that prompted this post, we have a bunch of client clusters (that we manage with argocd), and we want to deploy the datadog cluster agent via a helm chart + khelm to these clusters. This is straightforward when we use khelm, but the chart requires a `clusterName` value. This value gets turned into a `DD_CLUSTER_NAME` env var in 5 different containers. I can use the chart in a base and pass `clusterName: replaceme` to make the chart succeed, but then I need to add patches to two update all of those locations, for each consumer. Essentially that's this about 18 times:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../bases/datadog
patches:
  - patch: |-
      op: replace
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: datadog-cluster-agent
      spec:
        template:
          spec:
            containers:
              - name: cluster-agent
                env:
                  - name: DD_CLUSTER_NAME
                    value: my-cluster
  - patch: |-
      op: replace
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: datadog
      spec:
        template:
          spec:
            initContainers:
              - name: init-config
                env:
                  - name: DD_CLUSTER_NAME
                    value: my-cluster
            containers:
              - name: agent
                env:
                  - name: DD_CLUSTER_NAME
                    value: my-cluster
              - name: process-agent
                env:
                  - name: DD_CLUSTER_NAME
                    value: my-cluster
              - name: system-probe
                env:
                  - name: DD_CLUSTER_NAME
                    value: my-cluster
```
