### ISSUE TITLE
[QUESTION] Does khelm support oci helm registries?

### ISSUE THREAD

**Issue by milpog** [mgoltzsche/khelm#46]
Some projects like https://karpenter.sh are only publishing helm charts to oci. Those registries are supported from [Helm v3.8.0](https://helm.sh/docs/topics/registries/). I couldn't make khelm working with this type of registry.

- chart configuration
```yaml
apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
metadata:
  name: karpenter
  namespace: kube-system
repository: "oci://public.ecr.aws/karpenter"
chart: karpenter
version: 0.19.2
```

- command to render helm chart
```bash
export KHELM_TRUST_ANY_REPO=true
kustomize build --enable-alpha-plugins . > karpenter yaml
```

- error message
```
Running khelm 2.2.1 (helm 3.10.1)
Using repository "oci://public.ecr.aws/karpenter" (unauthenticated)
Downloading repository index of oci://public.ecr.aws/karpenter
khelm: load chart karpenter: looks like "oci://public.ecr.aws/karpenter" is not a valid chart repository or cannot be reached: object required
```
