### ISSUE TITLE
[BUG] cert-manager 1.11.0: "chart requires kubeVersion: >= 1.21.0-0 which is incompatible with Kubernetes v1.20.0"

### ISSUE THREAD

**Issue by JamesClonk** [mgoltzsche/khelm#48]
**Describe the bug**
The latest cert-manager helm chart (v1.11.0) has the property `kubeVersion: ">= 1.21.0-0"` set since the newly release v1.11.0.
Trying to render that helm chart with khelm fails since then with the following error message:
```
$ kpt fn eval base -i mgoltzsche/khelm:latest --network --fn-config ./khelm.yaml --truncate-output=false
[RUNNING] "mgoltzsche/khelm:latest"
[FAIL] "mgoltzsche/khelm:latest" in 2s
  Stderr:
    "Running khelm 2.2.1 (helm 3.10.1)"
    "WARNING: using untrusted repository \"https://charts.jetstack.io\""
    "Downloading repository index of https://charts.jetstack.io"
    "Downloading chart cert-manager v1.11.0 from repo https://charts.jetstack.io"
    "Rendering chart cert-manager v1.11.0 with name \"cert-manager\" and namespace \"cert-manager\""
    "khelm: render chart cert-manager: chart requires kubeVersion: >= 1.21.0-0 which is incompatible with Kubernetes v1.20.0"
    ""
  Exit code: 1
```
There seems to be some kind of Kubernetes version checking going on when rendering Helm charts, and maybe some library somewhere inside khelm pretends to be K8s v1.20.0?

Doing the same with the previous cert-manager helm chart (v1.10.2) works without a problem.

**To Reproduce**
1. Create `khelm.yaml` for cert-manager v1.11.0:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  repository: https://charts.jetstack.io
  chart: cert-manager
  version: 1.11.0
  name: cert-manager
  namespace: cert-manager
```
2. Run `kpt fn eval base -i mgoltzsche/khelm:latest --network --fn-config ./khelm.yaml --truncate-output=false`
3. See error

**khelm version:**
- Running khelm via image `mgoltzsche/khelm:latest`.
- Using kpt 1.0.0-beta.24
