### ISSUE TITLE
[QUESTION] Setting kubeVersion in ChartRenderer

### ISSUE THREAD

**Issue by DanielWozniak94** [mgoltzsche/khelm#62]
I'm trying to upgrade the version of cert-manager that we are using from 1.10.0 to 1.13.0. However theres a requirement of having the kubeVersion be >= 1.22.0. Similar issue as in #48.

In order to mitigate this requirement I tried adding `kubeVersion: "1.22.0"` to the ChartRenderer manifest however it doesn't seem to be getting picked up as I still get the same error.

Heres an example ChartRenderer file that we have
```
apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
namespace: cert-manager
metadata:
  name: cert-manager
repository: https://charts.jetstack.io
chart: cert-manager
version: "1.13.0"
kubeVersion: "1.22.0"
values:
  fullnameOverride: cert-manager
  installCRDs: true
  ...
```

We are using khelm version `2.2.1`.

Any idea what I might be doing wrong?
